models:
  - name: bronze_FactDCOILWTICO
    description: '{{ doc("bronze_FactDCOILWTICO") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactGASREGW
    description: '{{ doc("bronze_FactGASREGW") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactDPROPANEMBTX
    description: '{{ doc("bronze_FactDPROPANEMBTX") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactCPIAUCSL
    description: '{{ doc("bronze_FactCPIAUCSL") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactPPIACO
    description: '{{ doc("bronze_FactPPIACO") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactPCE
    description: '{{ doc("bronze_FactPCE") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactCPILFESL
    description: '{{ doc("bronze_FactCPILFESL") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactUMCSENT
    description: '{{ doc("bronze_FactUMCSENT") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactPCEPILFE
    description: '{{ doc("bronze_FactPCEPILFE") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactMICH
    description: '{{ doc("bronze_FactMICH") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactPAYEMS
    description: '{{ doc("bronze_FactPAYEMS") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactUNRATE
    description: '{{ doc("bronze_FactUNRATE") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactCES0500000003
    description: '{{ doc("bronze_FactCES0500000003") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactCIVPART
    description: '{{ doc("bronze_FactCIVPART") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactJTSJOL
    description: '{{ doc("bronze_FactJTSJOL") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactICSA
    description: '{{ doc("bronze_FactICSA") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactADPWNUSNERSA
    description: '{{ doc("bronze_FactADPWNUSNERSA") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactU6RATE
    description: '{{ doc("bronze_FactU6RATE") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactAWHNONAG
    description: '{{ doc("bronze_FactAWHNONAG") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactFEDFUNDS
    description: '{{ doc("bronze_FactFEDFUNDS") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactDFEDTAR
    description: '{{ doc("bronze_FactDFEDTAR") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactIOER
    description: '{{ doc("bronze_FactIOER") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactDISCOUNT
    description: '{{ doc("bronze_FactDISCOUNT") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactDGS10
    description: '{{ doc("bronze_FactDGS10") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactSOFR
    description: '{{ doc("bronze_FactSOFR") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactPRIME
    description: '{{ doc("bronze_FactPRIME") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactTB3MS
    description: '{{ doc("bronze_FactTB3MS") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactCPFF
    description: '{{ doc("bronze_FactCPFF") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactCSUSHPINSA
    description: '{{ doc("bronze_FactCSUSHPINSA") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactHSN1F
    description: '{{ doc("bronze_FactHSN1F") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactPERMIT
    description: '{{ doc("bronze_FactPERMIT") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactHOUST
    description: '{{ doc("bronze_FactHOUST") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactUSSTHPI
    description: '{{ doc("bronze_FactUSSTHPI") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactEXHOSLUSM495S
    description: '{{ doc("bronze_FactEXHOSLUSM495S") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactMORTGAGE30US
    description: '{{ doc("bronze_FactMORTGAGE30US") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactRRVRUSQ156N
    description: '{{ doc("bronze_FactRRVRUSQ156N") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactRHORUSQ156N
    description: '{{ doc("bronze_FactRHORUSQ156N") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_FactHOSINVUSM495N
    description: '{{ doc("bronze_FactHOSINVUSM495N") }}'
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: bronze_DimCategories
    description: This dimension table is the metadata that categorizes each series into binned groups determined at user input of data pipeline start. 
    columns:
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: Category
        description: '{{ doc("Category") }}'
  - name: bronze_DimSeries
    description: This dimension table is the metadata for each series and is defined by the FRED. 
    columns:
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: RealTimeStart
        description: '{{ doc("RealTimeStart") }}'
      - name: RealTimeEnd
        description: '{{ doc("RealTimeEnd") }}'
      - name: Name
        description: '{{ doc("Name") }}'
      - name: ObservationStart
        description: '{{ doc("ObservationStart") }}'
      - name: ObservationEnd
        description: '{{ doc("ObservationEnd") }}'
      - name: Frequency
        description: '{{ doc("Frequency") }}'
      - name: FrequencyAbbr
        description: '{{ doc("FrequencyAbbr") }}'
      - name: Units
        description: '{{ doc("Units") }}'
      - name: UnitsAbbr
        description: '{{ doc("UnitsAbbr") }}'
      - name: SeasAdj
        description: '{{ doc("SeasAdj") }}'
      - name: SeasAdjAbbr
        description: '{{ doc("SeasAdjAbbr") }}'
      - name: SeasAdjBool
        description: '{{ doc("SeasAdjBool") }}'
  - name: silver_FactSeries_unionall
    description: This table unions all bronze Fact tables into one vertical table.
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: silver_FactSeries_setdatatypes
    description: This table explicitly assigns datatypes to each column. 
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: FetchDate
        description: '{{ doc("FetchDate") }}'
  - name: silver_DimSeries_setdatatypes
    description: This table explicitly assigns datatypes to each column. 
    columns:
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: RealTimeStart
        description: '{{ doc("RealTimeStart") }}'
      - name: RealTimeEnd
        description: '{{ doc("RealTimeEnd") }}'
      - name: Name
        description: '{{ doc("Name") }}'
      - name: ObservationStart
        description: '{{ doc("ObservationStart") }}'
      - name: ObservationEnd
        description: '{{ doc("ObservationEnd") }}'
      - name: Frequency
        description: '{{ doc("Frequency") }}'
      - name: FrequencyAbbr
        description: '{{ doc("FrequencyAbbr") }}'
      - name: Units
        description: '{{ doc("Units") }}'
      - name: UnitsAbbr
        description: '{{ doc("UnitsAbbr") }}'
      - name: SeasAdj
        description: '{{ doc("SeasAdj") }}'
      - name: SeasAdjAbbr
        description: '{{ doc("SeasAdjAbbr") }}'
      - name: SeasAdjBool
        description: '{{ doc("SeasAdjBool") }}'
  - name: silver_DimSeries_binaryconversion
    description: This table adds a column of data for Seasonality Adjustment (True/False). 
    columns:
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: RealTimeStart
        description: '{{ doc("RealTimeStart") }}'
      - name: RealTimeEnd
        description: '{{ doc("RealTimeEnd") }}'
      - name: Name
        description: '{{ doc("Name") }}'
      - name: ObservationStart
        description: '{{ doc("ObservationStart") }}'
      - name: ObservationEnd
        description: '{{ doc("ObservationEnd") }}'
      - name: Frequency
        description: '{{ doc("Frequency") }}'
      - name: FrequencyAbbr
        description: '{{ doc("FrequencyAbbr") }}'
      - name: Units
        description: '{{ doc("Units") }}'
      - name: UnitsAbbr
        description: '{{ doc("UnitsAbbr") }}'
      - name: SeasAdj
        description: '{{ doc("SeasAdj") }}'
      - name: SeasAdjAbbr
        description: '{{ doc("SeasAdjAbbr") }}'
      - name: SeasAdjBool
        description: '{{ doc("SeasAdjBool") }}'
  - name: silver_DimCategories_setdatatypes
    description: This table explicitly assigns datatypes to each column. 
    columns:
      - name: SeriesID
        description: '{{ doc("SeriesID") }}'
      - name: Category
        description: '{{ doc("Category") }}'
  - name: gold_freddata
    description: This is the final table of all series and is ready for analytics ingestion. 
    columns:
      - name: Date
        description: '{{ doc("Date") }}'
      - name: Series
        description: '{{ doc("Series") }}'
      - name: Name
        description: '{{ doc("Name") }}'
      - name: Frequency
        description: '{{ doc("Frequency") }}'
      - name: Units
        description: '{{ doc("Units") }}'
      - name: SeasonallyAdjusted
        description: '{{ doc("SeasAdj") }}'
      - name: Category
        description: '{{ doc("Category") }}'
